//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppControl_Escolar.WS_Usuario_Reference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Usuario_Reference.WS_UsuarioSoap")]
    public interface WS_UsuarioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SELECT_Usuario(string id, string nombre, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_Usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SELECT_UsuarioAsync(string id, string nombre, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_UserEmpleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SELECT_UserEmpleado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_UserEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SELECT_UserEmpleadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DELETE_Usuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE_Usuario", ReplyAction="*")]
        System.Threading.Tasks.Task DELETE_UsuarioAsync(int id);
        
        // CODEGEN: Parameter 'Admin' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioResponse UPDATE_Usuario(AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE_Usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioResponse> UPDATE_UsuarioAsync(AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioRequest request);
        
        // CODEGEN: Parameter 'Admin' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioResponse INSERT_Usuario(AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_Usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioResponse> INSERT_UsuarioAsync(AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UPDATE_Usuario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UPDATE_UsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Admin;
        
        public UPDATE_UsuarioRequest() {
        }
        
        public UPDATE_UsuarioRequest(int IdUsuario, string Usuario, string Password, System.Nullable<int> Admin) {
            this.IdUsuario = IdUsuario;
            this.Usuario = Usuario;
            this.Password = Password;
            this.Admin = Admin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UPDATE_UsuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UPDATE_UsuarioResponse {
        
        public UPDATE_UsuarioResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="INSERT_Usuario", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class INSERT_UsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdEmpleado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Admin;
        
        public INSERT_UsuarioRequest() {
        }
        
        public INSERT_UsuarioRequest(int IdEmpleado, string Usuario, string Password, System.Nullable<int> Admin) {
            this.IdEmpleado = IdEmpleado;
            this.Usuario = Usuario;
            this.Password = Password;
            this.Admin = Admin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="INSERT_UsuarioResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class INSERT_UsuarioResponse {
        
        public INSERT_UsuarioResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_UsuarioSoapChannel : AppControl_Escolar.WS_Usuario_Reference.WS_UsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_UsuarioSoapClient : System.ServiceModel.ClientBase<AppControl_Escolar.WS_Usuario_Reference.WS_UsuarioSoap>, AppControl_Escolar.WS_Usuario_Reference.WS_UsuarioSoap {
        
        public WS_UsuarioSoapClient() {
        }
        
        public WS_UsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_UsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_UsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_UsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SELECT_Usuario(string id, string nombre, string usuario) {
            return base.Channel.SELECT_Usuario(id, nombre, usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SELECT_UsuarioAsync(string id, string nombre, string usuario) {
            return base.Channel.SELECT_UsuarioAsync(id, nombre, usuario);
        }
        
        public System.Data.DataSet SELECT_UserEmpleado() {
            return base.Channel.SELECT_UserEmpleado();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SELECT_UserEmpleadoAsync() {
            return base.Channel.SELECT_UserEmpleadoAsync();
        }
        
        public void DELETE_Usuario(int id) {
            base.Channel.DELETE_Usuario(id);
        }
        
        public System.Threading.Tasks.Task DELETE_UsuarioAsync(int id) {
            return base.Channel.DELETE_UsuarioAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioResponse AppControl_Escolar.WS_Usuario_Reference.WS_UsuarioSoap.UPDATE_Usuario(AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioRequest request) {
            return base.Channel.UPDATE_Usuario(request);
        }
        
        public void UPDATE_Usuario(int IdUsuario, string Usuario, string Password, System.Nullable<int> Admin) {
            AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioRequest inValue = new AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioRequest();
            inValue.IdUsuario = IdUsuario;
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.Admin = Admin;
            AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioResponse retVal = ((AppControl_Escolar.WS_Usuario_Reference.WS_UsuarioSoap)(this)).UPDATE_Usuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioResponse> AppControl_Escolar.WS_Usuario_Reference.WS_UsuarioSoap.UPDATE_UsuarioAsync(AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioRequest request) {
            return base.Channel.UPDATE_UsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioResponse> UPDATE_UsuarioAsync(int IdUsuario, string Usuario, string Password, System.Nullable<int> Admin) {
            AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioRequest inValue = new AppControl_Escolar.WS_Usuario_Reference.UPDATE_UsuarioRequest();
            inValue.IdUsuario = IdUsuario;
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.Admin = Admin;
            return ((AppControl_Escolar.WS_Usuario_Reference.WS_UsuarioSoap)(this)).UPDATE_UsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioResponse AppControl_Escolar.WS_Usuario_Reference.WS_UsuarioSoap.INSERT_Usuario(AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioRequest request) {
            return base.Channel.INSERT_Usuario(request);
        }
        
        public void INSERT_Usuario(int IdEmpleado, string Usuario, string Password, System.Nullable<int> Admin) {
            AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioRequest inValue = new AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioRequest();
            inValue.IdEmpleado = IdEmpleado;
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.Admin = Admin;
            AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioResponse retVal = ((AppControl_Escolar.WS_Usuario_Reference.WS_UsuarioSoap)(this)).INSERT_Usuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioResponse> AppControl_Escolar.WS_Usuario_Reference.WS_UsuarioSoap.INSERT_UsuarioAsync(AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioRequest request) {
            return base.Channel.INSERT_UsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioResponse> INSERT_UsuarioAsync(int IdEmpleado, string Usuario, string Password, System.Nullable<int> Admin) {
            AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioRequest inValue = new AppControl_Escolar.WS_Usuario_Reference.INSERT_UsuarioRequest();
            inValue.IdEmpleado = IdEmpleado;
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            inValue.Admin = Admin;
            return ((AppControl_Escolar.WS_Usuario_Reference.WS_UsuarioSoap)(this)).INSERT_UsuarioAsync(inValue);
        }
    }
}
