//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppControl_Escolar.WS_Materia_Reference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Materia_Reference.WS_MateriaSoap")]
    public interface WS_MateriaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_Materia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SELECT_Materia(string id, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_Materia", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SELECT_MateriaAsync(string id, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE_Materia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DELETE_Materia(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE_Materia", ReplyAction="*")]
        System.Threading.Tasks.Task DELETE_MateriaAsync(int id);
        
        // CODEGEN: Parameter 'Creditos' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE_Materia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaResponse UPDATE_Materia(AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE_Materia", ReplyAction="*")]
        System.Threading.Tasks.Task<AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaResponse> UPDATE_MateriaAsync(AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaRequest request);
        
        // CODEGEN: Parameter 'Creditos' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_Materia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaResponse INSERT_Materia(AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_Materia", ReplyAction="*")]
        System.Threading.Tasks.Task<AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaResponse> INSERT_MateriaAsync(AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UPDATE_Materia", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UPDATE_MateriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdMateria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Creditos;
        
        public UPDATE_MateriaRequest() {
        }
        
        public UPDATE_MateriaRequest(int IdMateria, string Nombre, System.Nullable<int> Creditos) {
            this.IdMateria = IdMateria;
            this.Nombre = Nombre;
            this.Creditos = Creditos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UPDATE_MateriaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UPDATE_MateriaResponse {
        
        public UPDATE_MateriaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="INSERT_Materia", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class INSERT_MateriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Creditos;
        
        public INSERT_MateriaRequest() {
        }
        
        public INSERT_MateriaRequest(string Nombre, System.Nullable<int> Creditos) {
            this.Nombre = Nombre;
            this.Creditos = Creditos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="INSERT_MateriaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class INSERT_MateriaResponse {
        
        public INSERT_MateriaResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_MateriaSoapChannel : AppControl_Escolar.WS_Materia_Reference.WS_MateriaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_MateriaSoapClient : System.ServiceModel.ClientBase<AppControl_Escolar.WS_Materia_Reference.WS_MateriaSoap>, AppControl_Escolar.WS_Materia_Reference.WS_MateriaSoap {
        
        public WS_MateriaSoapClient() {
        }
        
        public WS_MateriaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_MateriaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_MateriaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_MateriaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SELECT_Materia(string id, string nombre) {
            return base.Channel.SELECT_Materia(id, nombre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SELECT_MateriaAsync(string id, string nombre) {
            return base.Channel.SELECT_MateriaAsync(id, nombre);
        }
        
        public void DELETE_Materia(int id) {
            base.Channel.DELETE_Materia(id);
        }
        
        public System.Threading.Tasks.Task DELETE_MateriaAsync(int id) {
            return base.Channel.DELETE_MateriaAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaResponse AppControl_Escolar.WS_Materia_Reference.WS_MateriaSoap.UPDATE_Materia(AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaRequest request) {
            return base.Channel.UPDATE_Materia(request);
        }
        
        public void UPDATE_Materia(int IdMateria, string Nombre, System.Nullable<int> Creditos) {
            AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaRequest inValue = new AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaRequest();
            inValue.IdMateria = IdMateria;
            inValue.Nombre = Nombre;
            inValue.Creditos = Creditos;
            AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaResponse retVal = ((AppControl_Escolar.WS_Materia_Reference.WS_MateriaSoap)(this)).UPDATE_Materia(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaResponse> AppControl_Escolar.WS_Materia_Reference.WS_MateriaSoap.UPDATE_MateriaAsync(AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaRequest request) {
            return base.Channel.UPDATE_MateriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaResponse> UPDATE_MateriaAsync(int IdMateria, string Nombre, System.Nullable<int> Creditos) {
            AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaRequest inValue = new AppControl_Escolar.WS_Materia_Reference.UPDATE_MateriaRequest();
            inValue.IdMateria = IdMateria;
            inValue.Nombre = Nombre;
            inValue.Creditos = Creditos;
            return ((AppControl_Escolar.WS_Materia_Reference.WS_MateriaSoap)(this)).UPDATE_MateriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaResponse AppControl_Escolar.WS_Materia_Reference.WS_MateriaSoap.INSERT_Materia(AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaRequest request) {
            return base.Channel.INSERT_Materia(request);
        }
        
        public void INSERT_Materia(string Nombre, System.Nullable<int> Creditos) {
            AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaRequest inValue = new AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaRequest();
            inValue.Nombre = Nombre;
            inValue.Creditos = Creditos;
            AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaResponse retVal = ((AppControl_Escolar.WS_Materia_Reference.WS_MateriaSoap)(this)).INSERT_Materia(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaResponse> AppControl_Escolar.WS_Materia_Reference.WS_MateriaSoap.INSERT_MateriaAsync(AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaRequest request) {
            return base.Channel.INSERT_MateriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaResponse> INSERT_MateriaAsync(string Nombre, System.Nullable<int> Creditos) {
            AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaRequest inValue = new AppControl_Escolar.WS_Materia_Reference.INSERT_MateriaRequest();
            inValue.Nombre = Nombre;
            inValue.Creditos = Creditos;
            return ((AppControl_Escolar.WS_Materia_Reference.WS_MateriaSoap)(this)).INSERT_MateriaAsync(inValue);
        }
    }
}
