USE ControlEscolar;

INSERT INTO Tipo_acentamiento(Nombre) VALUES
('Aeropuerto'),
('Ampliación'),
('Barrio'),
('Campamento'),
('Club de golf'),
('Colonia'),
('Condominio'),
('Congregación'),
('Conjunto habitacional'),
('Ejido'),
('Equipamiento'),
('Estación'),
('Exhacienda'),
('Finca'),
('Fraccionamiento'),
('Gran usuario'),
('Granja'),
('Hacienda'),
('Ingenio'),
('Paraje'),
('Parque industrial'),
('Poblado comunal'),
('Pueblo'),
('Puerto'),
('Ranchería'),
('Rancho'),
('Residencial'),
('Unidad habitacional'),
('Villa'),
('Zona comercial'),
('Zona federal'),
('Zona industrial'),
('Zona militar'),
('Zona naval');
