//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppControl_Escolar.WS_Auditoria_Reference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Auditoria_Reference.WS_AuditoriaSoap")]
    public interface WS_AuditoriaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_Auditoria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SELECT_Auditoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_Auditoria", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SELECT_AuditoriaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_AuditoriaSoapChannel : AppControl_Escolar.WS_Auditoria_Reference.WS_AuditoriaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_AuditoriaSoapClient : System.ServiceModel.ClientBase<AppControl_Escolar.WS_Auditoria_Reference.WS_AuditoriaSoap>, AppControl_Escolar.WS_Auditoria_Reference.WS_AuditoriaSoap {
        
        public WS_AuditoriaSoapClient() {
        }
        
        public WS_AuditoriaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_AuditoriaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_AuditoriaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_AuditoriaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SELECT_Auditoria() {
            return base.Channel.SELECT_Auditoria();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SELECT_AuditoriaAsync() {
            return base.Channel.SELECT_AuditoriaAsync();
        }
    }
}
