//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppControl_Escolar.WS_Empleado_Reference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Empleado_Reference.WS_EmpleadoSoap")]
    public interface WS_EmpleadoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_Empleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SELECT_Empleado(string id, string nombre, string puesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_Empleado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SELECT_EmpleadoAsync(string id, string nombre, string puesto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_IEmpleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SELECT_IEmpleado(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_IEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SELECT_IEmpleadoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_Puesto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SELECT_Puesto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_Puesto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SELECT_PuestoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE_Empleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DELETE_Empleado(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE_Empleado", ReplyAction="*")]
        System.Threading.Tasks.Task DELETE_EmpleadoAsync(int id);
        
        // CODEGEN: Parameter 'Telefono' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE_Empleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoResponse UPDATE_Empleado(AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE_Empleado", ReplyAction="*")]
        System.Threading.Tasks.Task<AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoResponse> UPDATE_EmpleadoAsync(AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoRequest request);
        
        // CODEGEN: Parameter 'Telefono' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_Empleado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoResponse INSERT_Empleado(AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_Empleado", ReplyAction="*")]
        System.Threading.Tasks.Task<AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoResponse> INSERT_EmpleadoAsync(AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UPDATE_Empleado", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UPDATE_EmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdEmpleado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string APaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string AMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Fecha_nacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Sexo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string Calle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string Numero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Celular;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string Correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdAcentamiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdPuesto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string Grado_estudios;
        
        public UPDATE_EmpleadoRequest() {
        }
        
        public UPDATE_EmpleadoRequest(int IdEmpleado, string Nombre, string APaterno, string AMaterno, string Fecha_nacimiento, string Sexo, string Calle, string Numero, System.Nullable<int> Telefono, System.Nullable<int> Celular, string Correo, System.Nullable<int> IdAcentamiento, System.Nullable<int> IdPuesto, string Grado_estudios) {
            this.IdEmpleado = IdEmpleado;
            this.Nombre = Nombre;
            this.APaterno = APaterno;
            this.AMaterno = AMaterno;
            this.Fecha_nacimiento = Fecha_nacimiento;
            this.Sexo = Sexo;
            this.Calle = Calle;
            this.Numero = Numero;
            this.Telefono = Telefono;
            this.Celular = Celular;
            this.Correo = Correo;
            this.IdAcentamiento = IdAcentamiento;
            this.IdPuesto = IdPuesto;
            this.Grado_estudios = Grado_estudios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UPDATE_EmpleadoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UPDATE_EmpleadoResponse {
        
        public UPDATE_EmpleadoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="INSERT_Empleado", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class INSERT_EmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string APaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string AMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Fecha_nacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Sexo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Calle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string Numero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Celular;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string Correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdAcentamiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdPuesto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string Grado_estudios;
        
        public INSERT_EmpleadoRequest() {
        }
        
        public INSERT_EmpleadoRequest(string Nombre, string APaterno, string AMaterno, string Fecha_nacimiento, string Sexo, string Calle, string Numero, System.Nullable<int> Telefono, System.Nullable<int> Celular, string Correo, System.Nullable<int> IdAcentamiento, System.Nullable<int> IdPuesto, string Grado_estudios) {
            this.Nombre = Nombre;
            this.APaterno = APaterno;
            this.AMaterno = AMaterno;
            this.Fecha_nacimiento = Fecha_nacimiento;
            this.Sexo = Sexo;
            this.Calle = Calle;
            this.Numero = Numero;
            this.Telefono = Telefono;
            this.Celular = Celular;
            this.Correo = Correo;
            this.IdAcentamiento = IdAcentamiento;
            this.IdPuesto = IdPuesto;
            this.Grado_estudios = Grado_estudios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="INSERT_EmpleadoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class INSERT_EmpleadoResponse {
        
        public INSERT_EmpleadoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_EmpleadoSoapChannel : AppControl_Escolar.WS_Empleado_Reference.WS_EmpleadoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_EmpleadoSoapClient : System.ServiceModel.ClientBase<AppControl_Escolar.WS_Empleado_Reference.WS_EmpleadoSoap>, AppControl_Escolar.WS_Empleado_Reference.WS_EmpleadoSoap {
        
        public WS_EmpleadoSoapClient() {
        }
        
        public WS_EmpleadoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_EmpleadoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_EmpleadoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_EmpleadoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SELECT_Empleado(string id, string nombre, string puesto) {
            return base.Channel.SELECT_Empleado(id, nombre, puesto);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SELECT_EmpleadoAsync(string id, string nombre, string puesto) {
            return base.Channel.SELECT_EmpleadoAsync(id, nombre, puesto);
        }
        
        public System.Data.DataSet SELECT_IEmpleado(int id) {
            return base.Channel.SELECT_IEmpleado(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SELECT_IEmpleadoAsync(int id) {
            return base.Channel.SELECT_IEmpleadoAsync(id);
        }
        
        public System.Data.DataSet SELECT_Puesto() {
            return base.Channel.SELECT_Puesto();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SELECT_PuestoAsync() {
            return base.Channel.SELECT_PuestoAsync();
        }
        
        public void DELETE_Empleado(int id) {
            base.Channel.DELETE_Empleado(id);
        }
        
        public System.Threading.Tasks.Task DELETE_EmpleadoAsync(int id) {
            return base.Channel.DELETE_EmpleadoAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoResponse AppControl_Escolar.WS_Empleado_Reference.WS_EmpleadoSoap.UPDATE_Empleado(AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoRequest request) {
            return base.Channel.UPDATE_Empleado(request);
        }
        
        public void UPDATE_Empleado(int IdEmpleado, string Nombre, string APaterno, string AMaterno, string Fecha_nacimiento, string Sexo, string Calle, string Numero, System.Nullable<int> Telefono, System.Nullable<int> Celular, string Correo, System.Nullable<int> IdAcentamiento, System.Nullable<int> IdPuesto, string Grado_estudios) {
            AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoRequest inValue = new AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoRequest();
            inValue.IdEmpleado = IdEmpleado;
            inValue.Nombre = Nombre;
            inValue.APaterno = APaterno;
            inValue.AMaterno = AMaterno;
            inValue.Fecha_nacimiento = Fecha_nacimiento;
            inValue.Sexo = Sexo;
            inValue.Calle = Calle;
            inValue.Numero = Numero;
            inValue.Telefono = Telefono;
            inValue.Celular = Celular;
            inValue.Correo = Correo;
            inValue.IdAcentamiento = IdAcentamiento;
            inValue.IdPuesto = IdPuesto;
            inValue.Grado_estudios = Grado_estudios;
            AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoResponse retVal = ((AppControl_Escolar.WS_Empleado_Reference.WS_EmpleadoSoap)(this)).UPDATE_Empleado(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoResponse> AppControl_Escolar.WS_Empleado_Reference.WS_EmpleadoSoap.UPDATE_EmpleadoAsync(AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoRequest request) {
            return base.Channel.UPDATE_EmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoResponse> UPDATE_EmpleadoAsync(int IdEmpleado, string Nombre, string APaterno, string AMaterno, string Fecha_nacimiento, string Sexo, string Calle, string Numero, System.Nullable<int> Telefono, System.Nullable<int> Celular, string Correo, System.Nullable<int> IdAcentamiento, System.Nullable<int> IdPuesto, string Grado_estudios) {
            AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoRequest inValue = new AppControl_Escolar.WS_Empleado_Reference.UPDATE_EmpleadoRequest();
            inValue.IdEmpleado = IdEmpleado;
            inValue.Nombre = Nombre;
            inValue.APaterno = APaterno;
            inValue.AMaterno = AMaterno;
            inValue.Fecha_nacimiento = Fecha_nacimiento;
            inValue.Sexo = Sexo;
            inValue.Calle = Calle;
            inValue.Numero = Numero;
            inValue.Telefono = Telefono;
            inValue.Celular = Celular;
            inValue.Correo = Correo;
            inValue.IdAcentamiento = IdAcentamiento;
            inValue.IdPuesto = IdPuesto;
            inValue.Grado_estudios = Grado_estudios;
            return ((AppControl_Escolar.WS_Empleado_Reference.WS_EmpleadoSoap)(this)).UPDATE_EmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoResponse AppControl_Escolar.WS_Empleado_Reference.WS_EmpleadoSoap.INSERT_Empleado(AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoRequest request) {
            return base.Channel.INSERT_Empleado(request);
        }
        
        public void INSERT_Empleado(string Nombre, string APaterno, string AMaterno, string Fecha_nacimiento, string Sexo, string Calle, string Numero, System.Nullable<int> Telefono, System.Nullable<int> Celular, string Correo, System.Nullable<int> IdAcentamiento, System.Nullable<int> IdPuesto, string Grado_estudios) {
            AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoRequest inValue = new AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoRequest();
            inValue.Nombre = Nombre;
            inValue.APaterno = APaterno;
            inValue.AMaterno = AMaterno;
            inValue.Fecha_nacimiento = Fecha_nacimiento;
            inValue.Sexo = Sexo;
            inValue.Calle = Calle;
            inValue.Numero = Numero;
            inValue.Telefono = Telefono;
            inValue.Celular = Celular;
            inValue.Correo = Correo;
            inValue.IdAcentamiento = IdAcentamiento;
            inValue.IdPuesto = IdPuesto;
            inValue.Grado_estudios = Grado_estudios;
            AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoResponse retVal = ((AppControl_Escolar.WS_Empleado_Reference.WS_EmpleadoSoap)(this)).INSERT_Empleado(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoResponse> AppControl_Escolar.WS_Empleado_Reference.WS_EmpleadoSoap.INSERT_EmpleadoAsync(AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoRequest request) {
            return base.Channel.INSERT_EmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoResponse> INSERT_EmpleadoAsync(string Nombre, string APaterno, string AMaterno, string Fecha_nacimiento, string Sexo, string Calle, string Numero, System.Nullable<int> Telefono, System.Nullable<int> Celular, string Correo, System.Nullable<int> IdAcentamiento, System.Nullable<int> IdPuesto, string Grado_estudios) {
            AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoRequest inValue = new AppControl_Escolar.WS_Empleado_Reference.INSERT_EmpleadoRequest();
            inValue.Nombre = Nombre;
            inValue.APaterno = APaterno;
            inValue.AMaterno = AMaterno;
            inValue.Fecha_nacimiento = Fecha_nacimiento;
            inValue.Sexo = Sexo;
            inValue.Calle = Calle;
            inValue.Numero = Numero;
            inValue.Telefono = Telefono;
            inValue.Celular = Celular;
            inValue.Correo = Correo;
            inValue.IdAcentamiento = IdAcentamiento;
            inValue.IdPuesto = IdPuesto;
            inValue.Grado_estudios = Grado_estudios;
            return ((AppControl_Escolar.WS_Empleado_Reference.WS_EmpleadoSoap)(this)).INSERT_EmpleadoAsync(inValue);
        }
    }
}
